### ISSUE TITLE
No license file or mention to one !

### ISSUE THREAD

**Issue by mingodad** [pfalcon/squirrel-modules#1]
Hello !

Can you add a license file or a clear mention to the license you want to apply to your own code ?

Cheers !

**Comment by pfalcon** [comment]
Ack. It's the same license as Squirrel itself, i.e. MIT. Please remind me in a week if I haven't added an explicit LICENSE file by then.

**Comment by pfalcon** [comment]
Added now.

Also, I'm sure you're aware, but just in case: I'm no longer work on Squirrel, and instead work on MicroPython: https://github.com/micropython/micropython . It's both more advanced technically and based on a well-known language (great knowledge and experience reuse).
